---
title: "R Notebook - prepping data for assignment"
output:
  html_document:
    df_print: paged
---
Setting up my R environment

```{r}
library(dplyr)
library(tidyr)

```

First, trying to import the XLSX of country_info


```{r}
library(readxl)

country_info = read_excel("originalData/country-info.xlsx")

sapply(country_info, class)
head(country_info)

```

Second, import and view owid-covid-data

```{r}

originalCovid = read.csv("originalData/owid-covid-data-28112020.csv")

sapply(originalCovid, class)
head(originalCovid)

```

Join the two datasets

```{r}

mergedData <- originalCovid %>%
          mutate(date = as.Date(date, format = "%Y-%m-%d")) %>%
          inner_join(country_info, c("location" = "COUNTRY") )


class(mergedData$date)

head(mergedData)
```

Step 1: Change the column names to be smaller so that it can show better on the plots we create later.

```{r}

#Set up names
names(mergedData)

hist(mergedData$date,breaks="month")

#newNames <- 

#<- aggregate() for groupings. By location, collapses ev

```

